name: Eta
on:
  push:
    branches:
      - "eta"
  workflow_dispatch:
jobs:
  eta:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - name: Run script
        run: bash ${{secrets.ETA_SCRIPT}}
